// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_config.proto

#ifndef PROTOBUF_test_5fconfig_2eproto__INCLUDED
#define PROTOBUF_test_5fconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace test {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_test_5fconfig_2eproto();
void protobuf_AssignDesc_test_5fconfig_2eproto();
void protobuf_ShutdownFile_test_5fconfig_2eproto();

class TestConfig;

// ===================================================================

class TestConfig : public ::google::protobuf::Message {
 public:
  TestConfig();
  virtual ~TestConfig();

  TestConfig(const TestConfig& from);

  inline TestConfig& operator=(const TestConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestConfig& default_instance();

  void Swap(TestConfig* other);

  // implements Message ----------------------------------------------

  TestConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestConfig& from);
  void MergeFrom(const TestConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required int32 print_times = 2;
  inline bool has_print_times() const;
  inline void clear_print_times();
  static const int kPrintTimesFieldNumber = 2;
  inline ::google::protobuf::int32 print_times() const;
  inline void set_print_times(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:test.TestConfig)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_print_times();
  inline void clear_has_print_times();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::int32 print_times_;
  friend void  protobuf_AddDesc_test_5fconfig_2eproto();
  friend void protobuf_AssignDesc_test_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_test_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static TestConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// TestConfig

// required string name = 1;
inline bool TestConfig::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestConfig::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestConfig::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestConfig::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& TestConfig::name() const {
  // @@protoc_insertion_point(field_get:test.TestConfig.name)
  return *name_;
}
inline void TestConfig::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:test.TestConfig.name)
}
inline void TestConfig::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:test.TestConfig.name)
}
inline void TestConfig::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test.TestConfig.name)
}
inline ::std::string* TestConfig::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:test.TestConfig.name)
  return name_;
}
inline ::std::string* TestConfig::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TestConfig::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:test.TestConfig.name)
}

// required int32 print_times = 2;
inline bool TestConfig::has_print_times() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestConfig::set_has_print_times() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestConfig::clear_has_print_times() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestConfig::clear_print_times() {
  print_times_ = 0;
  clear_has_print_times();
}
inline ::google::protobuf::int32 TestConfig::print_times() const {
  // @@protoc_insertion_point(field_get:test.TestConfig.print_times)
  return print_times_;
}
inline void TestConfig::set_print_times(::google::protobuf::int32 value) {
  set_has_print_times();
  print_times_ = value;
  // @@protoc_insertion_point(field_set:test.TestConfig.print_times)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace test

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_5fconfig_2eproto__INCLUDED
